version: "3.9"
services:
  chat:
    image: ${CHAT_PROJECT_NAME}
    container_name: ${CHAT_PROJECT_NAME}
    restart: unless-stopped
#    ports:
#      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      traefik:
        ipv4_address: 172.24.0.10
      chat:
      postgres:
    environment:
      DB_URL: "${DB_URL}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      APP_URL: "${CHAT_PROJECT_NAME}.${TRAEFIK_HOST_SUFFIX}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CHAT_PROJECT_NAME}.rule=Host(`${CHAT_PROJECT_NAME}.${TRAEFIK_HOST_SUFFIX}`)"
      - "traefik.http.routers.${CHAT_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${CHAT_PROJECT_NAME}.service=${CHAT_PROJECT_NAME}"
      - "traefik.http.routers.${CHAT_PROJECT_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${CHAT_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
  chat:
    external: true
  postgres:
    external: true
